CREATE TABLE EMP (
  ENO integer,
  ENAME text,
  SAL integer,
  COMM integer,
  JOB text,
  HIEREDATE text,
  DEPTNO integer );

INSERT INTO EMP VALUES(1,'SMITH',800,150,'CLERK','10-DEC-80',10);
INSERT INTO EMP VALUES(2,'ALLEN',1600,null,'SALESMAN','15-JAN-87',20);
INSERT INTO EMP VALUES(3,'KING',5000,300,'PRESIDENT','20-FEB-92',30);
INSERT INTO EMP VALUES(4,'WARD',2975,125,'CLERK','17-MAR-84',10);
INSERT INTO EMP VALUES(5,'REMEO',3000,1400,'SALESMAN','26-APR-81',20);
INSERT INTO EMP VALUES(6,'JULITES',2600,NULL,'MANAGER','15-MAR-85',10);

SELECT* FROM EMP;

SELECT * FROM EMP WHERE SAL>1000;

SELECT ENAME,SAL,DEPTNO FROM EMP WHERE JOB='SALESMAN';

SELECT* FROM EMP WHERE ENAME='SMITH';

SELECT ENAME, HIEREDATE
FROM EMP
WHERE (HIEREDATE, 'DD-MON-YY') > ('31-DEC-1980', 'DD-MON-YY');

SELECT * FROM EMP WHERE (HIEREDATE,'DD-MON-YY') < ('01-JAN-1987','DD-MON-YY');

SELECT SAL*12 AS ANNUAL_SAL FROM EMP WHERE ENAME='SMITH';

SELECT* FROM EMP WHERE (DEPTNO=10 OR DEPTNO=20) AND JOB='PRESIDENT';

SELECT * FROM EMP WHERE JOB='CLERK';

SELECT SAL FROM EMP WHERE JOB='SALESMAN';

SELECT* FROM EMP WHERE SAL>2000;

SELECT* FROM EMP WHERE SAL>400 AND JOB='PRESIDENT';

SELECT ENAME, SAL*12 AS ANNUAL_SAL FROM EMP WHERE JOB='MANAGER' AND DEPTNO=10;

SELECT* FROM EMP WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30;

SELECT* FROM EMP WHERE JOB='SALESMAN' OR JOB='ANALYST';